server:
  port: 8081

signup:
  method: POST
  url: /api/auth/signup
  param:
    loginId: orijoon98
    password: AAbb12!!
    name: joon
    email: orijoon98@gmail.com

login:
  method: POST
  url: /api/auth/login
  param:
    loginId: orijoon98
    password: AAbb12!!

verify:
  method: POST
  url: /api/auth/verify

getVerify:
  method: GET
  url: /api/auth/verify/

delete:
  method: DELETE
  url: /api/auth/delete
  param:
    loginId: user

updateUserPublic:
  method: PUT
  url: /api/user/public
  param:
    country: Korea
    birthday: 1998-02-05
    gender: male
    zipCode: 04588
    address: 23, Cheonggu-ro 1-gil, Jung-gu, Seoul, Republic of Korea
    detailAddress: 101-1
    number: 02-1234-5678
    phoneNumber: 010-1234-5678

updateUserPrivate:
  method: PUT
  url: /api/user/private
  param:
    bank: shinhan
    accountNumber: 454111-05-519143
    accountHolder: user
    note:
